# Доступные зачеия Exporters:
# ClientLic - Клиентские лицензии
# AvailablePerformance - Доступная производительность (через RAC)
# SheduleJob - Проверка галки "блокировка регламентных заданий"
# Session - Сеансы
# Connect - Соединения
# SessionsData - Различные показарели из консоли 1с  (через RAC)
# ProcData - Данные поцессов (получается из ОС, пока поддерживается только linux)
# CPU   - Загрузка ЦПУ
# disk  - Метрики диска, пока только linux и WeightedIO
# Property - Доп. свойства, у каждой метрики свои могут быть
# у ProcData доп. свойство processes определяет список процессов которые нужно мониторить
Exporters:
  - Name: client_lic
  - Name: available_performance
  - Name: processes
  - Name: cpu
  - Name: disk
  - Name: shedule_job
  - Name: session
  - Name: connect
  - Name: sessions_data


# http-сервис который возвращает массив json с кредами к БД
# нужно для метрики SheduleJob
# пример json:
#[
#  {
#    "Name": "hrmcorp-n17",
#    "UserName": "",
#    "UserPass": ""
#  }
#]
DBCredentials: # опциональный параметр для метрики shedule_job
  URL: http://ca-fr-web-1/fresh/int/sm/hs/PTG_SysExchange/GetDatabase
  User: ""
  Password: ""
  TLSSkipVerify: true # если true, то при обращении к сервису будут игнорироваться ошибки проверки сертификата

RAC:
  Path: "C:\\Program Files\\1cv8\\8.3.21.1644\\bin\\rac.exe"
  Port: "1545"      # Не обязательный параметр
  Host: "localhost" # Не обязательный параметр
  Login: ""         # Не обязательный параметр
  Pass: ""          # Не обязательный параметр

MetricKinds:
  # Для метрики количества сессий можно задать, в каком виде будут данные предоставлены (настройка типа Строка).
  # Варианты настроек: "Summary", "Gauge", "NativeHistogram"
  # По умолчанию (без введенной настройки), метрика отдается в виде Summary.
  Session: ["Summary"]
  # Данные о сессиях могут предоставлены в виде Summary, с детализацией по каждой сессии. Это режим "по умолчанию", если настройка не указана.
  # Также можно предоставлять данные в более агрегированном виде, в виде гистограммы. При этом используется разновидность гистограмм - Native histogram.
  # Можно указать оба режима вывода, перечислением режимом в массиве.
  SessionsData: ["Summary", "NativeHistogram"]

LogDir:        # Если на задан, то логи будут писаться в каталог с исполняемым файлом
LogLevel:  5   # Уровень логирования от 2 до 5, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг

# Дополнительные настройки
Other:
  # Опциональный префикс имени метки (Строка). Например, чтобы все метрики экспортера были как-то сгруппированы в списке метрик.
  MetricNamePrefix: "p1c_"
  # Можно отключить сбор метрик клиента go (метрики с именами go_*)
  DisableGoCollector: true