# Доступные зачеия Exporters:
# ClientLic - Клиентские лицензии
# AvailablePerformance - Доступная производительность (через RAC)
# SheduleJob - Проверка галки "блокировка регламентных заданий"
# Session - Сеансы
# Connect - Соединения
# SessionsData - Различные показарели из консоли 1с  (через RAC)
# ProcData - Данные поцессов (получается из ОС, пока поддерживается только linux)
# CPU   - Загрузка ЦПУ
# disk  - Метрики диска, пока только linux и WeightedIO
# Property - Доп. свойства, у каждой метрики свои могут быть
# у ProcData доп. свойство processes определяет список процессов которые нужно мониторить
Exporters:
  - Name: client_lic
  - Name: available_performance
  - Name: processes
  - Name: cpu
  - Name: disk
  - Name: shedule_job
  - Name: session
  - Name: connect
  - Name: sessions_data


# http-сервис который возвращает массив json с кредами к БД
# нужно для метрики SheduleJob
# пример json:
#[
#  {
#    "Name": "hrmcorp-n17",
#    "UserName": "",
#    "UserPass": ""
#  }
#]
DBCredentials: # обязательный параметр для метрики shedule_job
  URL: http://ca-fr-web-1/fresh/int/sm/hs/PTG_SysExchange/GetDatabase
  User: ""
  Password: ""
  TLSSkipVerify: true # если true, то при обращении к сервису будут игнорироваться ошибки проверки сертификата

RAC:
  Path: "C:\\Program Files\\1cv8\\8.3.21.1644\\bin\\rac.exe"
  Port: "1545"      # Необязательный параметр
  Host: "localhost" # Необязательный параметр
  Login: ""         # Необязательный параметр
  Pass: ""          # Необязательный параметр

CollectModes:
  # Для метрики количества сессий можно задать, в каком виде будут данные предоставлены (настройка типа Строка). 
  # Варианты настроек: "SessionsHistogram", "SessionsGauge", "SessionsHistogramAndGauge"
  # По умолчанию (без введенной настройки), метрика отдается в виде Summary. Также, это соответствует настройке "SessionsHistogram".
  # Но можно отдавать в виде Gauge. При этом дополнительно будет разбивка по app-id (виду приложения 1С). 
  # Для этого необходимо задать значение настройки "SessionsGauge" (будет отдаваться только gauge) 
  # или "SessionsHistogramAndGauge" (будет отдаваться и summary, и gauge).
  Sessions: "SessionsHistogramAndGauge" 

LogDir:        # Если не задан, то логи будут писаться в каталог с исполняемым файлом
LogLevel:  5   # Уровень логирования от 2 до 5, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг

# Модификаторы для меток
LabelModes:
  # Опциональный префикс имени метки (Строка). Например, чтобы все метрики экспортера были как-то сгруппированы в списке метрик.
  MetricNamePrefix: "p1c_"
  # Брать ли имя хоста (метка host) из настроек RAS/RAC (настройка типа Булево).
  # При false (по умолчанию), имя метки устанавливается именем хоста, на котором работает экспортер. 
  # При true, имя метки устанавливается из настроек RAS, в формате "[ras host]:[ras port]"
  UseHostFromRAS: false